--CREATE TABLE STATUS
CREATE TABLE STATUS(
   STATUS_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
   LABEL VARCHAR2(10) NOT NULL
);

--CREATE SEQUENCE STATUS_SEQ
CREATE SEQUENCE STATUS_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE; 


 --CREATE TABLE INV_STATUS
CREATE TABLE inv_status(
	STATUS_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
   LABEL VARCHAR2(10) NOT NULL
);

--CREATE SEQUENCE STATUS_INV_SEQ
CREATE SEQUENCE STATUS_INV_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE; 


--CREATE TABLE SUPPLIERS
CREATE TABLE SUPPLIERS(
   SUPPLIERS_ID VARCHAR2(10) NOT NULL,
   SUP_NAME VARCHAR2(50) NOT NULL,
   SUP_ADDRESS VARCHAR2(100) NOT NULL,
   SUP_EMAIL VARCHAR2(50) NOT NULL,
   SUP_CONTACT_NUMBER VARCHAR2(20) NOT NULL,
   SUP_CONTACT_NAME VARCHAR2(50) NOT NULL,

   PRIMARY KEY(SUPPLIERS_ID)
);

--CREATE SEQUENCE SUPPLIER_SEQ FOR PRIMARY KEY
CREATE SEQUENCE SUPPLIER_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

 --CREATE TABLE ORDERS
CREATE TABLE ORDERS(
   OR_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
   OR_REF VARCHAR2(20) NOT NULL,
   OR_DATE DATE NOT NULL,
   OR_STATUS VARCHAR2(9) NOT NULL,
   OR_DESC VARCHAR2(250) NOT NULL,
   SUPPLIERS_ID VARCHAR2(10) NOT NULL,
   TOTAL_AMOUNT NUMBER(10, 2),
   FOREIGN KEY(SUPPLIERS_ID) REFERENCES SUPPLIERS(SUPPLIERS_ID)
);

--CREATE SEQUENCE ORDERS_SEQ
CREATE SEQUENCE ORDERS_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

 --CREATE TABLE ORDERS_DETAIL
CREATE TABLE ORDERS_DETAIL(
   OR_D_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
   OR_D_LINE_AMOUNT NUMBER(10, 2) NOT NULL,
   OR_D_DESC VARCHAR2(255),
   OR_D_REF VARCHAR2(20),
   OR_ID VARCHAR2(10) NOT NULL,
   STATUS_ID VARCHAR2(10) NOT NULL,
   FOREIGN KEY(OR_ID) REFERENCES ORDERS(OR_ID),
   FOREIGN KEY(STATUS_ID) REFERENCES STATUS(STATUS_ID)
);

----CREATE SEQUENCE ORDERS_DETAIL_SEQ
CREATE SEQUENCE ORDERS_DETAIL_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

--CREATE TABLE INVOICE
CREATE TABLE INVOICE(
   INV_ID VARCHAR2(10) NOT NULL PRIMARY KEY,
   INV_REF VARCHAR2(20) ,
   INV_DATE DATE,
   INV_STATUS VARCHAR2(20), --need to be removed
   INV_HOLD_REASON VARCHAR2(50),
   INV_DESC VARCHAR2(255),
   INV_AMOUNT NUMBER(10, 2),
   OR_ID VARCHAR2(10),
   SUPPLIERS_ID VARCHAR2(10) NOT NULL,
   FOREIGN KEY(SUPPLIERS_ID) REFERENCES SUPPLIERS(SUPPLIERS_ID),
   FOREIGN KEY(OR_ID) REFERENCES ORDERS(OR_ID),
   FOREIGN KEY(INV_STATUS) REFERENCES inv_status(STATUS_ID)
);

--CREATE SEQUENCE INVOICE_SEQ
CREATE SEQUENCE INVOICE_SEQ
   START WITH 1
   INCREMENT BY 1
   NOCACHE;
